import type { IndicatorDefinition } from "../data/types";
import { INDICATOR_IDS } from "./indicatorIds";

export const INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  {
    id: INDICATOR_IDS.SMA_14,
    label: "SMA 14",
    type: "sma",
    period: 14,
    color: "#f0b90b",
    defaultActive: false,
    overlay: true,
  },
  {
    id: INDICATOR_IDS.SMA_50,
    label: "SMA 50",
    type: "sma",
    period: 50,
    color: "#1abc9c",
    defaultActive: false,
    overlay: true,
  },
  {
    id: INDICATOR_IDS.EMA_20,
    label: "EMA 20",
    type: "ema",
    period: 20,
    color: "#f472b6",
    overlay: true,
  },
  {
    id: INDICATOR_IDS.EMA_50,
    label: "EMA 50",
    type: "ema",
    period: 50,
    color: "#ec4899",
    overlay: true,
  },
  {
    id: INDICATOR_IDS.EMA_200,
    label: "EMA 200",
    type: "ema",
    period: 200,
    color: "#d946ef",
    overlay: true,
  },
  {
    id: INDICATOR_IDS.EMA_95,
    label: "EMA 95",
    type: "ema",
    period: 95,
    color: "#0ea5e9",
    overlay: true,
  },
  {
    id: INDICATOR_IDS.ATR_14,
    label: "ATR 14",
    type: "atr",
    period: 14,
    color: "#fb923c",
    lineWidth: 2,
    overlay: false,
  },
  {
    id: INDICATOR_IDS.RSI_14,
    label: "RSI 14",
    type: "rsi",
    period: 14,
    color: "#a78bfa",
    lineWidth: 2,
    overlay: false,
  },
  {
    id: INDICATOR_IDS.ADX_14,
    label: "ADX 14",
    type: "adx",
    period: 14,
    color: "#38bdf8",
    lineWidth: 2,
    overlay: false,
  },
];
